server:
  port: 8012
  servlet:
    context-path: /
spring:
  application:
    name: consumer-demo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka,http://127.0.0.1:8083/eureka
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 30

# 选用不同的负载均衡策略
# user-service:
  # ribbon:
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule