server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: consumer-demo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8002/eureka,http://127.0.0.1:8003/eureka
