server:
  # 先启动8082，注册8083端口
  port: 8082
# port: 8083

# 服务的名称
spring:
  application:
    name: eureka-server

# 客户端地址，用于自身注册
eureka:
  client:
    service-url:
      # defaultZone: http://127.0.0.1:8083/eureka
      defaultZone: http://127.0.0.1:8082/eureka
    # 是否需要注册自身信息，默认为true
    # register-with-eureka: false
  server:
    # eureka server清理无效节点的时间间隔，默认是60000毫秒，即60秒
    eviction-interval-timer-in-ms: 60000
    # 当Eureka Server节点在短时间内丢失过多客户端时（可能发生了网络分区故障）
    # 那么这个节点就会进入自我保护模式
    # 一旦进入该模式，Eureka Server就会保护服务注册表中的信息
    # 不再删除服务注册表中的数据（也就是不会注销任何微服务）
    # 当网络故障恢复后，该Eureka Server节点会自动退出自我保护模式
    # Eureka会统计服务实例最近15分钟心跳续约的比例是否低于85%
    enable-self-preservation: true